export class Po {
  annual_delivery_date: string;
  auto_reject: string;
  commission: string;
  customer_code: number;
  distribution_channel: string;
  drf_link: string;
  drf_log: null;
  email_sender: string;
  freight_condition: string;
  gst_value: number;
  mail_code: number;
  po_date: string;
  po_link: string;
  po_log: string;
  po_no: string;
  pmt_id: string;
  r100: any;
  sales_org_name: string;
  sh: number;
  so_link: string;
  so_no: string;
  sp: string;
  status: string;
  timestamp: string;
  value: number;
  customer_name: string;
  sch_div_date: string;
}
